version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: ["--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    volumes:
      - './database/migrations:/docker-entrypoint-initdb.d'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USERNAME=root
      - ADMINER_DEFAULT_PASSWORD=root
      - ADMINER_DEFAULT_DATABESE=mydatabase